### PR TITLE
Tools update

### LINKED ISSUE #6: Software - Heidi
child of #1

### LINKED ISSUE #7: Software - DB Forge
child of #1

### LINKED ISSUE #17: Software - MySQL
child of #1

### LINKED ISSUE #60: Add "Installing extra components" to MySQL
So we have something to reference when we say "go install MySQL for Excel".

### PR DESCRIPTION
**Pull request by dave-mills**
Updated and tidied tools documents: 
 - OtherSQLClients.md organised and tweaked
 - DbForge.md added.
 - Heidi / MySQL standardised to use the What/Why/Install structure.

closes #60 
closes #7 
closes #17 
closes #6

### CODE REVIEW

**Comment by chrismclarke** [comment]
**dbForge** - again I can't see menu links so wondering if this is an incomplete commit? Otherwise looks good, change external links to open in a new tab (wrap with an <a href="..." target="_blank">...</a> tag. Also be aware that the farmer-plot-trial links may change after the merge (I can't remember what stayed step-3/5 and what moved)...

**Comment by chrismclarke** [comment]
**Mysql** - a bit of first person but I like its use so happy to make an exception. One dead image after group replication. Discussion on good practice for root user could link to relevant concepts page.

**Heidi** - remove link to localhost as that won't work for a user clicking. Possibly rephrase choice of collation mode to present options (i.e. many of these options will work fine however for consistency we recommend you choose either:
- _utf8_unicode_ci_ - this is a standard character encoding used by most modern programmes to allow all standard latin characters (e.g. A-Z, 0-9, !"3$%^) as well as most foreign characters (e.g. é, ö, π)
- utf8mb4 - this extends the list above to also include emoji characters (probably not required for your data but still nice to know! 😆)

**Both** - make download links open in new tabs, further references are blank so one or two short links (even if just to official docs page) would be good to have

**Comment by dave-mills** [comment]
I think I've addressed these in the latest commits: 
 - fixed images in MySQL
 - added words on collation mode in Heidi
 - made downloads and general links open in new tabs
 - added further references to docs pages for MySQL, Heidi, DbForge,

**Comment by dave-mills** [comment]
I think this is now good to go?

**Pull request merged**
