### PR TITLE
New concept pages

### LINKED ISSUE #2: DB Concepts - table structures
child of #1

### LINKED ISSUE #3: DB Concepts - Relationships
child of #1

### LINKED ISSUE #4: DB Concepts - What/Why DBs

### LINKED ISSUE #11: Best Practice - Table Structure
child of #1

### PR DESCRIPTION
**Pull request by dave-mills**
New and updated pages:
 - Database-setup
 - Relationships
 - Building tables
closes #2, 
closes #3, 
closes #4,
closes #11,

### CODE REVIEW

**Comment by chrismclarke** [comment]
Database setup (see commit) - minor edits at start and then shortened some of the section on root user (think better to promote 'keep the password safe as an organisation' rather than logistics of multiple data managers/password services etc. I'm wondering if it's also worth mentioning that root passwords can still be reset if lost (assuming access to the server)...? what do you think @dave-mills

**Comment by chrismclarke** [comment]
Relationships - Please change the diagrams so they read correctly left->right (e.g many->one and one(secondary) -> one (primary). Possibly also add text to the tables to indicate which they are (many/one/primary/secondary). Also could you add a diagram of many-to-many without the link table to make it clear that is how the situation starts and then is later resolved

I've also removed references found to first person 'I' - worth keeping an eye out for too

**Comment by dave-mills** [comment]
> I'm wondering if it's also worth mentioning that root passwords can still be reset if lost (assuming access to the server)...? what do you think @dave-mills

I think probably not worth mentioning here. So far we've avoided any use of command-line stuff. (I don't think there's a way without the terminal?) 

I think maybe at some future point there's a "Help, I'm stuck ... " document we could write, FAQ style, that could include resetting root passwords, resolutions of common potential errors, gotchas etc.

**Comment by dave-mills** [comment]
Looks good to me. Nice language tweaks / clarifications on various bits. I've made the updates you've suggested - I think this is ready to go?

**Comment by chrismclarke** [comment]
If I were to nit-pick I'd say remove the spellcheck red lines from images (but I won't!)

**Pull request merged**
